// ======================================
// aircraft.js
// Arrival Aircraft Database
// ======================================

const aircraft = [

{
    callsign: "AFL515",
    ssr: "6763",
    type: "B747",
    from: "VGHS",
    route: "R416",
    ccbETA: "11:18",
    entryRadial: 70,
    heading: 250,
    targetHeading: 250,
    level: 180,
    targetLevel: 180,
    speed: 490,
    labelAngle: 0,
    turnDirection: "SHORTEST",
    verticalSpeed: -1500,
    active: false,
    spawned: false,
    distance: 60,
    x: 0,
    y: 0,
    history: []
},

{
    callsign: "CLX044",
    ssr: "6755",
    type: "B747",
    from: "ELLX",
    route: "G473",
    ccbETA: "11:21",
    entryRadial: 300,
    heading: 120,
    targetHeading: 120,
    level: 180,
    targetLevel: 180,
    speed: 490,
    labelAngle: 45,
    turnDirection: "SHORTEST",
    verticalSpeed: -1500,
    active: false,
    spawned: false,
    distance: 60,
    x: 0,
    y: 0,
    history: []
},

{
    callsign: "AIC412",
    ssr: "6737",
    type: "A321",
    from: "VOMM",
    route: "B425",
    ccbETA: "11:24",
    entryRadial: 190,
    heading: 10,
    targetHeading: 10,
    level: 180,
    targetLevel: 180,
    speed: 460,
    labelAngle: 90,
    turnDirection: "SHORTEST",
    verticalSpeed: -1500,
    active: false,
    spawned: false,
    distance: 60,
    x: 0,
    y: 0,
    history: []
},

{
    callsign: "VU-CGQ",
    ssr: "",
    type: "HN74",
    from: "VICG",
    route: "W14",
    ccbETA: "11:27",
    entryRadial: 350,
    heading: 170,
    targetHeading: 170,
    level: 150,
    targetLevel: 150,
    speed: 210,
    labelAngle: 135,
    turnDirection: "SHORTEST",
    verticalSpeed: 0,
    active: false,
    spawned: false,
    distance: 60,
    x: 0,
    y: 0,
    history: []
},

{
    callsign: "THA715",
    ssr: "6713",
    type: "B747",
    from: "RPLL",
    route: "G473",
    ccbETA: "11:31",
    entryRadial: 120,
    heading: 300,
    targetHeading: 300,
    level: 180,
    targetLevel: 180,
    speed: 490,
    labelAngle: 180,
    turnDirection: "SHORTEST",
    verticalSpeed: -1500,
    active: false,
    spawned: false,
    distance: 60,
    x: 0,
    y: 0,
    history: []
},

{
    callsign: "CPA702",
    ssr: "6712",
    type: "B747",
    from: "OBBI",
    route: "G473",
    ccbETA: "11:34",
    entryRadial: 300,
    heading: 120,
    targetHeading: 120,
    level: 180,
    targetLevel: 180,
    speed: 490,
    labelAngle: 225,
    turnDirection: "SHORTEST",
    verticalSpeed: -1500,
    active: false,
    spawned: false,
    distance: 60,
    x: 0,
    y: 0,
    history: []
},

{
    callsign: "CG712",
    ssr: "6754",
    type: "DO228",
    from: "VOHY",
    route: "W20",
    ccbETA: "11:37",
    entryRadial: 170,
    heading: 350,
    targetHeading: 350,
    level: 80,
    targetLevel: 80,
    speed: 180,
    labelAngle: 270,
    turnDirection: "SHORTEST",
    verticalSpeed: 0,
    active: false,
    spawned: false,
    distance: 60,
    x: 0,
    y: 0,
    history: []
},

{
    callsign: "IGO440",
    ssr: "6764",
    type: "A320",
    from: "VIDP",
    route: "W14",
    ccbETA: "11:40",
    entryRadial: 350,
    heading: 170,
    targetHeading: 170,
    level: 180,
    targetLevel: 180,
    speed: 460,
    labelAngle: 315,
    turnDirection: "SHORTEST",
    verticalSpeed: -1500,
    active: false,
    spawned: false,
    distance: 60,
    x: 0,
    y: 0,
    history: []
}
];
